### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by rnicholls** [ninapavlich/ckeditor-image-caption#2]
Uncaught Error: [CKEDITOR.dialog.openDialog] Dialog "imagecaption" failed when loading definition.

**Comment by ninapavlich** [comment]
Hi @rnicholls,

I'm sorry to say that this plugin isn't actually production-ready -- I haven't been able to figure out how to compile it for CKEditor. I'll be sure to update the README to explain this. (Do you have any experience with this? I'd be happy to try to resolve this if you can point me in the right direction!)

It is available as part of this fork of CKEditor for Django (https://github.com/ninapavlich/django_ckeditor_improved). Looking at the source code there, you may be able to suss out a working version of what you're looking for.

Sorry about that!
